version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_backend
    ports:
      - "8080:8080"  # Expose Flask app on port 8080
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8080
    volumes:
      - ./app:/app  # Mount the app directory to persist any changes
      - ./sqlite_data:/app/db  # Mount the directory for the SQLite database
    depends_on: []
  
volumes:
  sqlite_data:
    driver: local
